#' Sunday Assembly Ritual Study Dataset
#'
#' A dataset from Charles et al. (2021) examining the effects of secular rituals
#' (Sunday Assemblies) on social bonding and affect, compared with Christian church
#' services. The study measured social bonding and affect before and after ritual
#' participation in a field study across multiple sites in the UK. This help
#' file was generated by Claude AI.
#'
#'
#' @format A data frame with 99 rows and 94 variables:
#' \describe{
#'   \item{participant_id}{Unique identifier for each participant}
#'   \item{sa_ctrl}{Ritual group indicator: Sunday Assembly or Church (control)}
#'   \item{ritual_site_id}{Identifier for the ritual site/location. Four Sunday
#'     Assemblies (Central London, Reading, Bristol, London East End) and four
#'     matched Christian churches were included}
#'   \item{synchrony_proxy}{Proxy measure of behavioral synchrony during the ritual}
#'   \item{length_mins}{Duration of the ritual in minutes}
#'   \item{total_attend}{Total attendance count (may represent number of participants
#'     or cumulative past attendance)}
#'
#'   \item{connected_change}{Change in feelings of connection from pre- to post-ritual
#'     (post minus pre)}
#'   \item{ios_change}{Change in Inclusion of Others in Self (IOS) scale score from
#'     pre- to post-ritual. IOS is measured on a 1-7 scale with overlapping circles}
#'   \item{emo_change}{Change in emotional closeness from pre- to post-ritual}
#'   \item{trust_change}{Change in trust towards other ritual participants from
#'     pre- to post-ritual}
#'   \item{like_change}{Change in liking of other participants from pre- to post-ritual}
#'   \item{common_change}{Change in perceived commonality with others from pre- to
#'     post-ritual}
#'   \item{sb6_change}{Change in social bonding item 6 from pre- to post-ritual}
#'   \item{panasp_change}{Change in positive affect (PANAS+) from pre- to post-ritual.
#'     Sum of 10 positive emotion items}
#'   \item{panasn_change}{Change in negative affect (PANAS-) from pre- to post-ritual.
#'     Sum of 10 negative emotion items}
#'
#'   \item{panas1_interested}{Pre-ritual rating of "interested" (0-5 scale)}
#'   \item{panas1_distressed}{Pre-ritual rating of "distressed" (0-5 scale)}
#'   \item{panas1_excited}{Pre-ritual rating of "excited" (0-5 scale)}
#'   \item{panas1_upset}{Pre-ritual rating of "upset" (0-5 scale)}
#'   \item{panas1_strong}{Pre-ritual rating of "strong" (0-5 scale)}
#'   \item{panas1_guilty}{Pre-ritual rating of "guilty" (0-5 scale)}
#'   \item{panas1_scared}{Pre-ritual rating of "scared" (0-5 scale)}
#'   \item{panas1_hostile}{Pre-ritual rating of "hostile" (0-5 scale)}
#'   \item{panas1_enthusiastic}{Pre-ritual rating of "enthusiastic" (0-5 scale)}
#'   \item{panas1_proud}{Pre-ritual rating of "proud" (0-5 scale)}
#'   \item{panas1_irritable}{Pre-ritual rating of "irritable" (0-5 scale)}
#'   \item{panas1_alert}{Pre-ritual rating of "alert" (0-5 scale)}
#'   \item{panas1_ashamed}{Pre-ritual rating of "ashamed" (0-5 scale)}
#'   \item{panas1_inspired}{Pre-ritual rating of "inspired" (0-5 scale)}
#'   \item{panas1_nervous}{Pre-ritual rating of "nervous" (0-5 scale)}
#'   \item{panas1_determined}{Pre-ritual rating of "determined" (0-5 scale)}
#'   \item{panas1_attentive}{Pre-ritual rating of "attentive" (0-5 scale)}
#'   \item{panas1_jittery}{Pre-ritual rating of "jittery" (0-5 scale)}
#'   \item{panas1_active}{Pre-ritual rating of "active" (0-5 scale)}
#'   \item{panas1_afraid}{Pre-ritual rating of "afraid" (0-5 scale)}
#'   \item{panasp_pre}{Pre-ritual positive affect composite score. Sum of 10 positive
#'     PANAS items (interested, excited, strong, enthusiastic, proud, alert, inspired,
#'     determined, attentive, active). Range: 0-50}
#'   \item{panasn_pre}{Pre-ritual negative affect composite score. Sum of 10 negative
#'     PANAS items (distressed, upset, guilty, scared, hostile, irritable, ashamed,
#'     nervous, jittery, afraid). Range: 0-50}
#'
#'   \item{s_bpre_connected}{Pre-ritual rating: "How connected do you feel to the
#'     people in this Sunday Assembly/congregation?" (1-7 Likert scale)}
#'   \item{s_bpre_emo_close}{Pre-ritual rating: "How emotionally close do you feel
#'     to the other members?" (1-7 Likert scale)}
#'   \item{s_bpre_trust}{Pre-ritual rating: "How much do you trust the others in
#'     this group?" (1-7 Likert scale)}
#'   \item{s_bpre_like}{Pre-ritual rating: "How much do you like the people in this
#'     Sunday Assembly/congregation overall?" (1-7 Likert scale)}
#'   \item{s_bpre_common}{Pre-ritual rating: "Do you feel you have a lot in common
#'     with others in this congregation?" (1-7 Likert scale)}
#'   \item{s_bpre_ios}{Pre-ritual Inclusion of Others in Self (IOS) scale rating
#'     (1-7 scale with overlapping circles)}
#'   \item{sb5_pre}{Pre-ritual social bonding item 5}
#'   \item{sb6_pre}{Pre-ritual social bonding composite score. Average of 6 social
#'     bonding items. Internal reliability α = .93 for Sunday Assembly, α = .94 for
#'     church participants}
#'
#'   \item{religiosity}{Self-rated religiosity (1-7 scale, where 1="Not at all" and
#'     7="Extremely so")}
#'   \item{spirituality}{Self-rated spirituality (1-7 scale, where 1="Not at all" and
#'     7="Extremely so"). Only collected for Sunday Assembly participants}
#'   \item{durel_church}{Duke University Religion Index (DUREL) - Organizational
#'     religious activity: "How often do you attend church or other religious meetings?"}
#'   \item{durel_private}{DUREL - Non-organizational religious activity: "How often
#'     do you spend time in private religious activities?"}
#'   \item{durel_divine}{DUREL - Intrinsic religiosity item about feeling God's
#'     divine presence}
#'   \item{durel_approach}{DUREL - Intrinsic religiosity item about religious approach
#'     to life}
#'   \item{durel_other}{DUREL - Other religiosity measure}
#'   \item{durel_3}{DUREL composite score for intrinsic religiosity (3 items)}
#'   \item{sec_durel_private}{Secondary measure of private religious activity}
#'   \item{sec_durel_meetings}{Secondary measure of attendance at religious meetings}
#'   \item{sec_durel_other}{Secondary measure of other religious involvement}
#'
#'   \item{panas2_interested}{Post-ritual rating of "interested" (0-5 scale)}
#'   \item{panas2_distressed}{Post-ritual rating of "distressed" (0-5 scale)}
#'   \item{panas2_excited}{Post-ritual rating of "excited" (0-5 scale)}
#'   \item{panas2_upset}{Post-ritual rating of "upset" (0-5 scale)}
#'   \item{panas2_strong}{Post-ritual rating of "strong" (0-5 scale)}
#'   \item{panas2_guilty}{Post-ritual rating of "guilty" (0-5 scale)}
#'   \item{panas2_scared}{Post-ritual rating of "scared" (0-5 scale)}
#'   \item{panas2_hostile}{Post-ritual rating of "hostile" (0-5 scale)}
#'   \item{panas2_enthusiastic}{Post-ritual rating of "enthusiastic" (0-5 scale)}
#'   \item{panas2_proud}{Post-ritual rating of "proud" (0-5 scale)}
#'   \item{panas2_irritable}{Post-ritual rating of "irritable" (0-5 scale)}
#'   \item{panas2_alert}{Post-ritual rating of "alert" (0-5 scale)}
#'   \item{panas2_ashamed}{Post-ritual rating of "ashamed" (0-5 scale)}
#'   \item{panas2_inspired}{Post-ritual rating of "inspired" (0-5 scale)}
#'   \item{panas2_nervous}{Post-ritual rating of "nervous" (0-5 scale)}
#'   \item{panas2_determined}{Post-ritual rating of "determined" (0-5 scale)}
#'   \item{panas2_attentive}{Post-ritual rating of "attentive" (0-5 scale)}
#'   \item{panas2_jittery}{Post-ritual rating of "jittery" (0-5 scale)}
#'   \item{panas2_active}{Post-ritual rating of "active" (0-5 scale)}
#'   \item{panas2_afraid}{Post-ritual rating of "afraid" (0-5 scale)}
#'   \item{panasp_post}{Post-ritual positive affect composite score. Sum of 10
#'     positive PANAS items. Range: 0-50}
#'   \item{panasn_post}{Post-ritual negative affect composite score. Sum of 10
#'     negative PANAS items. Range: 0-50}
#'
#'   \item{connected_bigger}{Post-ritual question: For Sunday Assembly - "Did you
#'     feel connected to something bigger than yourself, like the universe, and/or
#'     feel a sense of awe or wonder?" For Church - "Did you feel connected to God,
#'     Jesus, and/or the Holy Spirit?"}
#'   \item{s_bpost_connected}{Post-ritual rating: "How connected do you feel to the
#'     people in this Sunday Assembly/congregation?" (1-7 Likert scale)}
#'   \item{s_bpost_emo_close}{Post-ritual rating: "How emotionally close do you feel
#'     to the other members?" (1-7 Likert scale)}
#'   \item{s_bpost_trust}{Post-ritual rating: "How much do you trust the others in
#'     this group?" (1-7 Likert scale)}
#'   \item{s_bpost_like}{Post-ritual rating: "How much do you like the people in this
#'     Sunday Assembly/congregation overall?" (1-7 Likert scale)}
#'   \item{s_bpost_common}{Post-ritual rating: "Do you feel you have a lot in common
#'     with others in this congregation?" (1-7 Likert scale)}
#'   \item{s_bpost_ios}{Post-ritual Inclusion of Others in Self (IOS) scale rating
#'     (1-7 scale with overlapping circles)}
#'   \item{sb5_post}{Post-ritual social bonding item 5}
#'   \item{sb6_post}{Post-ritual social bonding composite score. Average of 6 social
#'     bonding items. Internal reliability α = .93 for Sunday Assembly, α = .89 for
#'     church participants}
#'
#'   \item{gender}{Gender identity (categorical)}
#'   \item{male}{Binary indicator for male gender identity (0/1)}
#'   \item{female}{Binary indicator for female gender identity (0/1)}
#'   \item{nb}{Binary indicator for non-binary gender identity (0/1)}
#'   \item{age}{Age in years. Sunday Assembly: M=39.6, SD=12.24; Church: M=57.8,
#'     SD=18.08; Overall: M=48.2, SD=18.21}
#'   \item{months}{Length of attendance in months (how long participant has been
#'     attending the Sunday Assembly or church)}
#'   \item{education}{Educational attainment level}
#' }
#'
#' @details
#' This dataset includes 99 participants (49 from Sunday Assemblies, 50 from churches)
#' collected across four Sunday Assembly sites in the UK (Central London, Reading,
#' Bristol, and London East End) and four matched Christian churches. The study used
#' a pre-post design measuring social bonding and affect before and after ritual
#' participation.
#'
#' ## Measures
#'
#' ### Social Bonding Scale
#' Six-item composite measure (sb6_pre, sb6_post) consisting of:
#' - Connection to group members (1-7 Likert)
#' - Emotional closeness (1-7 Likert)
#' - Trust (1-7 Likert)
#' - Liking (1-7 Likert)
#' - Perceived commonality (1-7 Likert)
#' - Inclusion of Others in Self (IOS) scale (1-7 pictorial scale)
#'
#' High internal reliability: α = .93 (Sunday Assembly pre), .93 (Sunday Assembly post),
#' .94 (Church pre), .89 (Church post)
#'
#' ### Positive and Negative Affect Scale (PANAS)
#' 20-item scale measuring current emotional state ("at this moment"):
#' - 10 positive emotions (interested, excited, strong, enthusiastic, proud, alert,
#'   inspired, determined, attentive, active)
#' - 10 negative emotions (distressed, upset, guilty, scared, hostile, irritable,
#'   ashamed, nervous, jittery, afraid)
#' - Each item rated 0-5 (0="not at all", 5="very much")
#' - Composite scores (panasp, panasn) are sums of respective items (range 0-50)
#'
#' ### Duke University Religion Index (DUREL)
#' Five-item measure assessing:
#' - Organizational religious activity (church attendance)
#' - Non-organizational religious activity (private practices)
#' - Intrinsic religiosity (3 items): divine presence, religious approach to life
#'
#' ## Key Findings
#' - Sunday Assembly attendance significantly increased social bonding (Z=5.02, p<.001,
#'   rR=.51, rK=.84)
#' - No significant difference in bonding increase between Sunday Assembly and church
#'   (interaction F(1,∞)=3.77, p=.052)
#' - Both groups showed increased positive affect and decreased negative affect
#' - Change in positive affect predicted change in social bonding (β=.70, p<.001)
#' - Connection to "something bigger" also predicted bonding change
#'
#' @source Charles, S.J., van Mulukom, V., Brown, J.E., Watts, F., Dunbar, R.I.M., &
#'   Farias, M. (2021). United on Sunday: The effects of secular rituals on social
#'   bonding and affect. PLOS ONE, 16(1), e0242546.
#'   \doi{10.1371/journal.pone.0242546}
#'
#' @references
#' Watson, D., Clark, L.A., & Tellegen, A. (1988). Development and validation of brief
#'   measures of positive and negative affect: the PANAS scales. Journal of Personality
#'   and Social Psychology, 54(6), 1063-1070.
#'
#' Aron, A., Aron, E.N., & Smollan, D. (1992). Inclusion of Other in the Self Scale and
#'   the structure of interpersonal closeness. Journal of Personality and Social
#'   Psychology, 63(4), 596-612.
#'
#' Koenig, H.G., & Büssing, A. (2010). The Duke University Religion Index (DUREL): A
#'   five-item measure for use in epidemiological studies. Religions, 1(1), 78-85.
#'
#' @examples
#' \dontrun{
#' # Load data
#' data(sunday_assembly_data)
#'
#' # Compare social bonding change between groups
#' library(ggplot2)
#' ggplot(sunday_assembly_data, aes(x = sa_ctrl, y = sb6_change)) +
#'   geom_boxplot() +
#'   labs(title = "Social Bonding Change by Group",
#'        x = "Group", y = "Change in Social Bonding")
#'
#' # Examine relationship between affect change and bonding change
#' library(dplyr)
#' sunday_assembly_data %>%
#'   ggplot(aes(x = panasp_change, y = sb6_change)) +
#'   geom_point() +
#'   geom_smooth(method = "lm") +
#'   facet_wrap(~sa_ctrl)
#'
#' # Reproduce main regression model (Sunday Assembly only)
#' sa_data <- sunday_assembly_data %>%
#'   filter(sa_ctrl == "Sunday Assembly")
#'
#' model <- lm(scale(sb6_change) ~ scale(panasp_change) + scale(panasn_change),
#'             data = sa_data)
#' summary(model)
#' }
#'
#' @keywords datasets ritual religion social-bonding affect PANAS wellbeing
"rituals"